environment:
  global:
    # Wrapper to ensure extensions are build using the MSVC compiler matching
    # the target Python version and architecture.
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: 'cmd /E:ON /V:ON /C .\tasks\run_with_env.cmd'

  matrix:
    - PYTHON: C:\Python27
      PYTHON_VERSION: 2.7
      PYTHON_ARCH: 32

  APPVEYOR_RDP_PASSWORD: Libsettings911!

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))


cache:
  # Cache downloaded pip packages and built wheels.
  - '%LOCALAPPDATA%\pip\Cache\http'
  - '%LOCALAPPDATA%\pip\Cache\wheels'
  # Chocolatey packages
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml


install:
  - cinst swig
  - cinst nsis
  - SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - set PATH=C:\MinGW\bin;%PATH%
  - python --version
  # Upgrade to the latest pip.
  - '%CMD_IN_ENV% python -m pip install -U pip setuptools wheel tox'
  - powershell .\\tasks\\missing-headers.ps1
  - md lib
  - cd lib
  - appveyor DownloadFile "https://raw.githubusercontent.com/swift-nav/libsettings/653f49e3fff51b14e367161e20ad59c406f9e4da/python/libsettings-0.1.0.tar.gz
  - md libsettings
  - tar -xzf libsettings-0.1.0.tar.gz -C libsettings --strip-components=1
  - cd libsettings
  - python setup.py build_ext --inplace --compiler=mingw32
  - cd ../..
  - '%CMD_IN_ENV% python scripts\build_release.py'

build: off

artifacts:
  - path: dist
    name: swift_console
  - path: dist
    name: cmd_line
